#server:
#  port: ${PORT:8081}
#
#spring:
#  application:
#    name: event
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/pi2g7
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#eureka:
#  instance:
#    hostname: localhost
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/