server:
  port : ${PORT:8761}

spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-adress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
