server:
  port: ${SERVER_PORT:9090}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/users/**
        - id: event
          uri: lb://event
          predicates:
            - Path=/events/**
  security:
    oauth2:
      client:
        # Configuration for the provider, in this case keycloak
        provider:
          ms-gateway:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        #Configuration to connect as a keycloack client
        registration:
          ms-gateway:
            provider: ms-gateway
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: ${OAUTH_SCOPE}
            authorization-grant-type: ${OAUTH_AUTH_GRANT_TYPE}
            redirect-uri: ${REDIRECT_URI} # OAuth2 standard format

jwt-decoder-url: ${JWT_DECODER_URL}
