name: Deploy to EC2

on:
  workflow_dispatch:
    # inputs:
    #   nombre:
    #     description: 'Nombre'

  # push:
  #   branches:
  #     - frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
      
      - name: Deploy to AWS
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r build/ ec2-user@${{ secrets.EC2_INSTANCE }}:/home/ec2-user
