name: Deploy to EC2

on:
  workflow_dispatch:
    # inputs:
    #   nombre:
    #     description: 'Nombre'

  # push:
  #   branches:
  #     - frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     # - name: Set up SSH key
     #   uses: webfactory/ssh-agent@v0.8.0
     #   with:
     #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     # - name: Install Dependencies and Build
     #   run: |
     #     cd frontend
     #     npm install
     #     npm run build

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_INSTANCE }}
          REMOTE_USER: ec2-user
          TARGET: /home/ec2-user
          
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd frontend
            npm install pm2 -g
            npm install
            npm run build
            pm2 start npm --name nextjs-app -- run start -- -p 3000
     
      #- name: Deploy to AWS
      #  run: |
      #    scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r build/ ec2-user@${{ secrets.EC2_INSTANCE }}:/home/ec2-user
