server:
  port : 8761

spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-adress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  logging:
    level:
      com:
        netflix:
          eureka: DEBUG
